name: Pull request branch check

on:
  pull_request:
    types:
      - opened
      - edited
    branches: ["main", "develop"]

jobs:
  pull_request_branch_check:
    name: Pull request branch check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set pull request branch variables
        run: |
          BASE_REF="${{ github.event.pull_request.base.ref }}"
          HEAD_REF="${{ github.event.pull_request.head.ref }}"
          echo "Base branch: $BASE_REF"
          echo "Head branch: $HEAD_REF"
          echo "BASE_REF=$BASE_REF" >> $GITHUB_ENV
          echo "HEAD_REF=$HEAD_REF" >> $GITHUB_ENV

      - name: Check pull request branch condition
        run: |
          if [ "$BASE_REF" == "main" ] && [[ "$HEAD_REF" != "develop" ]]; then
            echo "Pull request to the main branch can only be made from the develop branch."
            exit 1
          else
            echo "There is no issue with the pull request branch check."
          fi
